### ISSUE TITLE
Permutation

### ISSUE THREAD

**Issue by binh-vu** [rust-itertools/itertools#285]
Hi,

Thank you for making this awesome library. It would be great if you can support [permutate function like in python](https://docs.python.org/2/library/itertools.html#itertools.permutations)

Thanks!

**Comment by tobz1000** [comment]
I've implemented this function, and will put up a pull request soon, although I have no idea how long it'll be until merge.

In the meantime, you can use my branch in your Cargo.toml (or copy it to your fork) if you need it:
```toml
[dependencies]
itertools = { git = "https://github.com/tobz1000/rust-itertools", branch = "permutations" }
```
